In [1]:
import numpy as np
import pandas as pd

In [2]:
social_network = pd.read_csv("Social_Network_Ads.csv")
social_network

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
social_network.shape


(400, 5)

In [4]:
social_network.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
social_network.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [6]:
# #converting categorical values into numerical form


# varlist =  ['Gender']

# # Defining the map function
# def binary_map(x):
#     return x.map({'Male': 1, "Female": 0})

# # Applying the function to the housing list
# social_network[varlist] = social_network[varlist].apply(binary_map)

# # Printing the dataset after mapping
# social_network.head()

In [7]:
hot_data=pd.get_dummies(social_network,columns=['Gender'])
hot_data

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510   19            19000          0              0            1
1    15810944   35            20000          0              0            1
2    15668575   26            43000          0              1            0
3    15603246   27            57000          0              1            0
4    15804002   19            76000          0              0            1
..        ...  ...              ...        ...            ...          ...
395  15691863   46            41000          1              1            0
396  15706071   51            23000          1              0            1
397  15654296   50            20000          1              1            0
398  15755018   36            33000          0              0            1
399  15594041   49            36000          1              1            0

[400 rows x 6 columns]

In [8]:
hot_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Age              400 non-null    int64
 2   EstimatedSalary  400 non-null    int64
 3   Purchased        400 non-null    int64
 4   Gender_Female    400 non-null    uint8
 5   Gender_Male      400 non-null    uint8
dtypes: int64(4), uint8(2)
memory usage: 13.4 KB


In [9]:
hot_data.isnull().sum()

User ID            0
Age                0
EstimatedSalary    0
Purchased          0
Gender_Female      0
Gender_Male        0
dtype: int64

In [10]:
#model building
#splitting dataset into train and test data
x=hot_data.iloc[:,[1,2,4,5]]   #age,estimated salary and gender used 
y=hot_data.iloc[:,[3]]  #purchased will output

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25,random_state=0) 
print("75% training data set among the given dataset" , len(x_train))
print("25% testing data set among the given dataset" , len(x_test))

75% training data set among the given dataset 300
25% testing data set among the given dataset 100


In [12]:
# Data shuffling and getting 3 columns into specific continues range

from sklearn.preprocessing import StandardScaler
st_x=StandardScaler()
x_train=st_x.fit_transform(x_train)
x_test=st_x.fit_transform(x_test)


In [13]:
y_train

Purchased
250          0
63           1
312          0
159          1
283          1
..         ...
323          1
192          0
117          0
47           0
172          0

[300 rows x 1 columns]

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

/usr/local/lib64/python3.8/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [25]:
y_test

Purchased
132          0
309          0
341          0
196          0
246          0
..         ...
146          1
135          0
390          1
264          1
364          1

[100 rows x 1 columns]

In [26]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [17]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [20]:
from sklearn import metrics

# Confusion matrix 
confusion = metrics.confusion_matrix(y_true=y_test,y_pred=y_pred)
print(confusion)

[[64  4]
 [ 5 27]]


In [24]:
#Accuracy 
print(metrics.accuracy_score(y_test,y_pred))

0.91
